# Generated by Django 3.1.7 on 2021-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('rent', models.PositiveIntegerField()),
                ('bedroom', models.PositiveSmallIntegerField()),
                ('bathroom', models.PositiveSmallIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
