# Generated by Django 3.1.7 on 2021-05-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_info',
            field=models.TextField(default='SOME STRING', max_length=200),
        ),
    ]
