# Generated by Django 3.1.7 on 2021-05-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210509_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_BVcZpuy.jpg', upload_to='profile_pics'),
        ),
    ]
