# Generated by Django 3.1.7 on 2021-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210511_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blank-profile-picture-973460_640.png', upload_to='profile_pics'),
        ),
    ]
