# Generated by Django 3.1.7 on 2021-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210511_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_default.png', upload_to='profile_pics'),
        ),
    ]
